const http = require("http");
const { URL } = require("url");

const PORT = Number(process.env.PORT || 8000);

const COMMON_MOLECULES = {
  "CC(=O)Oc1ccccc1C(=O)O": {
    name: "Aspirin",
    molecular_formula: "C9H8O4",
    molecular_weight: 180.16,
    logp: 1.19,
    tpsa: 63.6,
    h_donors: 1,
    h_acceptors: 4,
    rotatable_bonds: 3,
    num_atoms: 13,
    num_bonds: 13,
    lipinski_violations: 0,
  },
  "CC(=O)Nc1ccc(O)cc1": {
    name: "Paracetamol",
    molecular_formula: "C8H9NO2",
    molecular_weight: 151.16,
    logp: 0.46,
    tpsa: 49.3,
    h_donors: 2,
    h_acceptors: 2,
    rotatable_bonds: 1,
    num_atoms: 11,
    num_bonds: 11,
    lipinski_violations: 0,
  },
  "CC(C)Cc1ccc(cc1)C(C)C(=O)O": {
    name: "Ibuprofen",
    molecular_formula: "C13H18O2",
    molecular_weight: 206.28,
    logp: 3.97,
    tpsa: 37.3,
    h_donors: 1,
    h_acceptors: 2,
    rotatable_bonds: 4,
    num_atoms: 15,
    num_bonds: 15,
    lipinski_violations: 0,
  },
  "Cn1cnc2c1c(=O)n(C)c(=O)n2C": {
    name: "Caffeine",
    molecular_formula: "C8H10N4O2",
    molecular_weight: 194.19,
    logp: -0.07,
    tpsa: 61.8,
    h_donors: 0,
    h_acceptors: 6,
    rotatable_bonds: 0,
    num_atoms: 14,
    num_bonds: 15,
    lipinski_violations: 0,
  },
  "CN1C=NC2=C1C(=O)N(C(=O)N2C)C": {
    name: "Caffeine",
    molecular_formula: "C8H10N4O2",
    molecular_weight: 194.19,
    logp: -0.07,
    tpsa: 61.8,
    h_donors: 0,
    h_acceptors: 6,
    rotatable_bonds: 0,
    num_atoms: 14,
    num_bonds: 15,
    lipinski_violations: 0,
  },
  "c1ccccc1": {
    name: "Benzene",
    molecular_formula: "C6H6",
    molecular_weight: 78.11,
    logp: 2.13,
    tpsa: 0,
    h_donors: 0,
    h_acceptors: 0,
    rotatable_bonds: 0,
    num_atoms: 6,
    num_bonds: 6,
    lipinski_violations: 0,
  },
  CCO: {
    name: "Ethanol",
    molecular_formula: "C2H6O",
    molecular_weight: 46.07,
    logp: -0.31,
    tpsa: 20.2,
    h_donors: 1,
    h_acceptors: 1,
    rotatable_bonds: 0,
    num_atoms: 3,
    num_bonds: 2,
    lipinski_violations: 0,
  },
  "OC[C@H]1OC(O)[C@H](O)[C@@H](O)[C@@H]1O": {
    name: "Glucose",
    molecular_formula: "C6H12O6",
    molecular_weight: 180.16,
    logp: -2.6,
    tpsa: 110.4,
    h_donors: 5,
    h_acceptors: 6,
    rotatable_bonds: 1,
    num_atoms: 12,
    num_bonds: 12,
    lipinski_violations: 0,
  },
};

const demoHistory = [];

function isLikelySmiles(smiles) {
  const s = String(smiles || "").trim();
  if (!s) return false;
  if (!/^[A-Za-z0-9@+\-=\\/()[\]#%.,:]+$/.test(s)) return false;
  let balance = 0;
  for (const ch of s) {
    if (ch === "(" || ch === "[") balance += 1;
    if (ch === ")" || ch === "]") balance -= 1;
    if (balance < 0) return false;
  }
  return balance === 0;
}

function moleculeInfo(smiles) {
  const s = String(smiles || "").trim();
  const known = COMMON_MOLECULES[s];
  if (known) return { valid: true, canonical_smiles: s, ...known };
  if (!isLikelySmiles(s)) return { valid: false, error: "Invalid SMILES syntax" };
  const atoms = (s.match(/[A-Z][a-z]?|[cnops]/g) || []).length || 1;
  const hetero = (s.match(/[NOSnos]/g) || []).length;
  return {
    valid: true,
    name: "Demo molecule",
    canonical_smiles: s,
    molecular_formula: "Demo",
    molecular_weight: Math.round((atoms * 12.4 + hetero * 8) * 100) / 100,
    logp: Math.round((1.2 + atoms * 0.12 - hetero * 0.25) * 100) / 100,
    tpsa: Math.round(hetero * 18.5 * 100) / 100,
    h_donors: Math.min(hetero, 3),
    h_acceptors: Math.min(hetero + 1, 8),
    rotatable_bonds: Math.max(0, Math.min(8, Math.floor(atoms / 4))),
    num_atoms: atoms,
    num_bonds: Math.max(0, atoms - 1),
    lipinski_violations: 0,
  };
}

function demoRoute(targetSmiles, index = 0) {
  const yieldPct = index === 0 ? 78.5 : 65.2;
  return {
    id: `demo-route-${index + 1}`,
    score: index === 0 ? 0.86 : 0.72,
    target_molecule: { smiles: targetSmiles },
    starting_materials: [
      { smiles: index === 0 ? "CC(=O)O" : "O=C(O)c1ccccc1" },
      { smiles: index === 0 ? "c1ccc(O)cc1" : "CO" },
    ],
    steps: [
      {
        id: `demo-step-${index + 1}-1`,
        reaction_type: index === 0 ? "esterification" : "amide coupling",
        difficulty: index === 0 ? "moderate" : "easy",
        estimated_yield_percent: yieldPct,
        estimated_cost_usd: index === 0 ? 42.5 : 58.25,
        reactants: [{ smiles: "CC(=O)O" }, { smiles: "c1ccc(O)cc1" }],
        product: { smiles: targetSmiles },
        conditions: {
          solvent: index === 0 ? "DCM" : "DMF",
          catalyst: index === 0 ? "H2SO4" : "EDC/HOBt",
          temperature_celsius: index === 0 ? 80 : 25,
          time_hours: index === 0 ? 4 : 2,
          pressure_atm: 1,
        },
        notes: "Demo route generated by the local fallback API.",
      },
    ],
    overall_yield_percent: yieldPct,
    total_cost_usd: index === 0 ? 125.75 : 168.4,
    total_time_hours: index === 0 ? 4.5 : 6,
    num_steps: 1,
    notes: "Local demo response. Start the Python backend for production-grade chemistry.",
  };
}

function retrosynthesis(target, maxRoutes = 3) {
  return Array.from({ length: Math.max(1, Math.min(maxRoutes, 3)) }, (_, i) => ({
    id: `retro-demo-${i + 1}`,
    target_smiles: target,
    total_score: Number((0.82 - i * 0.08).toFixed(2)),
    steps: [
      {
        reaction_type: i === 0 ? "acylation disconnection" : "functional group interconversion",
        transform: i === 0 ? "ester cleavage" : "late-stage derivatization",
        score: Number((0.8 - i * 0.06).toFixed(2)),
        precursors: i === 0 ? ["CC(=O)Cl", "c1ccc(O)cc1"] : ["O=C(O)c1ccccc1", "CO"],
        conditions: { solvent: "DCM", temperature_celsius: 25 },
      },
    ],
  }));
}

function constraints() {
  return {
    heat_risk: "low",
    heat_score: 0.18,
    mixing_efficiency: "good",
    mixing_score: 0.22,
    mass_transfer: "moderate",
    mass_transfer_score: 0.34,
    safety_risk: "low",
    safety_score: 0.2,
    purification_difficulty: "moderate",
    purification_score: 0.36,
    phase_complexity: "single phase",
    total_penalty: 0.28,
  };
}

function equipment(route) {
  const steps = Array.isArray(route?.steps) ? route.steps : [{}];
  return {
    feasible: true,
    overall_score: 86,
    step_equipment: steps.map((step, i) => ({
      step: i,
      reaction_type: step.reaction_type || "reaction",
      reactor: "jacketed glass reactor",
      score: 88 - i * 5,
    })),
    issues: [],
    recommendations: steps.map((step, i) => ({
      step: i,
      reaction_type: step.reaction_type || "reaction",
      equipment: "jacketed glass reactor",
    })),
  };
}

function mutations(route) {
  const cloned = JSON.parse(JSON.stringify(route || {}));
  cloned.mutations_applied = [
    {
      type: "solvent_step_1",
      original: cloned.steps?.[0]?.conditions?.solvent || "unknown",
      new: "2-MeTHF",
      reason: "Improves process safety and solvent recovery in demo mode.",
    },
  ];
  cloned.mutation_count = 1;
  if (cloned.steps?.[0]?.conditions) cloned.steps[0].conditions.solvent = "2-MeTHF";
  return cloned;
}

function json(status, body) {
  return {
    status,
    headers: {
      "content-type": "application/json",
      "access-control-allow-origin": "*",
      "access-control-allow-methods": "GET,POST,OPTIONS",
      "access-control-allow-headers": "content-type,x-api-key",
    },
    body: JSON.stringify(body),
  };
}

function readBody(req) {
  return new Promise((resolve) => {
    let raw = "";
    req.on("data", (chunk) => {
      raw += chunk;
    });
    req.on("end", () => {
      try {
        resolve(raw ? JSON.parse(raw) : {});
      } catch {
        resolve({});
      }
    });
  });
}

async function route(req) {
  const url = new URL(req.url, `http://${req.headers.host}`);
  const path = url.pathname;
  const body = req.method === "POST" ? await readBody(req) : {};

  if (req.method === "OPTIONS") return json(204, {});
  if (path === "/api/" || path === "/api/health") return json(200, { status: "ok", version: "demo-api" });
  if (path === "/api/auth/verify") return json(200, { status: "dev_mode" });

  if (path === "/api/molecule/validate") {
    const info = moleculeInfo(body.smiles);
    return json(200, info.valid ? { valid: true, canonical_smiles: info.canonical_smiles } : { valid: false, reason: info.error });
  }

  if (path === "/api/molecule/analyze") {
    const info = moleculeInfo(body.smiles);
    return info.valid ? json(200, info) : json(400, { detail: info.error });
  }

  if (path === "/api/synthesis/plan") {
    const target = body.target_smiles || body.smiles || "CC(=O)Oc1ccccc1C(=O)O";
    const routes = [demoRoute(target, 0), demoRoute(target, 1)].slice(0, Math.max(1, Math.min(2, Number(body.max_routes || 2))));
    const result = {
      request_id: `demo-${Date.now()}`,
      status: "success",
      target_smiles: target,
      routes,
      computation_time_seconds: 0.18,
      tokens_used: 0,
      timestamp: new Date().toISOString(),
    };
    demoHistory.unshift(result);
    return json(200, result);
  }

  if (path === "/api/synthesis/history") {
    const limit = Number(url.searchParams.get("limit") || 10);
    return json(200, { history: demoHistory.slice(0, limit) });
  }

  if (path === "/api/retrosynthesis/plan") {
    const target = body.target_smiles || "CC(=O)Oc1ccccc1C(=O)O";
    const routes = retrosynthesis(target, Number(body.max_routes || 3));
    return json(200, { status: "success", target_smiles: target, num_routes: routes.length, routes });
  }

  if (path === "/api/conditions/predict") {
    return json(200, {
      status: "success",
      conditions: {
        solvent: "2-MeTHF",
        catalyst: body.reaction_type?.includes("suzuki") ? "Pd(PPh3)4" : "H2SO4",
        temperature_celsius: body.reaction_type?.includes("hydrogenation") ? 25 : 80,
        pressure_atm: body.reaction_type?.includes("hydrogenation") ? 40 : 1,
        time_hours: 4,
      },
    });
  }

  if (path === "/api/routes/mutate") {
    const mutated = mutations(body.route);
    return json(200, { status: "success", original_route: body.route, mutated_route: mutated, mutations_applied: mutated.mutations_applied, mutation_count: 1 });
  }

  if (path === "/api/routes/constraint-feedback") {
    return json(200, {
      status: "success",
      original_constraints: { total_penalty: 0.42 },
      applied_fixes: [{ issue: "solvent", fix: "Switch to 2-MeTHF for safer scale-up." }],
      improved_constraints: { total_penalty: 0.24 },
      improvement_summary: "Demo optimization reduced the process penalty.",
      num_fixes: 1,
    });
  }

  if (path === "/api/routes/confidence") {
    return json(200, {
      status: "success",
      overall_confidence: 82,
      yield_confidence: 78,
      cost_confidence: 84,
      safety_confidence: 88,
      equipment_feasibility: 86,
      risk_level: "low",
      risk_factors: ["Uses demo confidence scoring"],
      reliability_breakdown: {},
    });
  }

  if (path === "/api/routes/equipment-check") {
    return json(200, { status: "success", ...equipment(body.route) });
  }

  if (path === "/api/routes/optimize") {
    const routeData = body.route || {};
    const mutated = mutations(routeData);
    return json(200, {
      status: "success",
      original_route: routeData,
      mutations: { applied: mutated.mutations_applied, count: 1 },
      constraint_feedback: {
        original: { total_penalty: 0.42 },
        fixes: [{ issue: "solvent", fix: "Switch to 2-MeTHF for safer scale-up." }],
        improved: { total_penalty: 0.24 },
        summary: "Demo optimization reduced process risk.",
      },
      confidence: {
        overall: 82,
        risk_level: "low",
        risk_factors: ["Demo scoring model"],
        breakdown: { yield: 78, cost: 84, safety: 88, equipment: 86 },
      },
      equipment: equipment(mutated),
      optimized_route: mutated,
    });
  }

  if (path === "/api/scale/optimize") {
    return json(200, {
      status: "success",
      optimization: {
        target_scale: body.target_scale || "lab",
        batch_size_kg: body.batch_size_kg || 0.1,
        recommended_temperature_celsius: 72,
        mixing: "overhead stirring",
        additions: "controlled addition over 30 minutes",
      },
    });
  }

  if (path === "/api/cost/industrial") {
    const size = Number(body.batch_size_kg || 0.1);
    return json(200, {
      status: "success",
      scale: body.scale || "lab",
      batch_size_kg: size,
      costs: {
        raw_material_usd: Number((size * 420).toFixed(2)),
        solvent_usd: Number((size * 85).toFixed(2)),
        labor_usd: Number((size * 140).toFixed(2)),
        total_usd: Number((size * 645).toFixed(2)),
      },
    });
  }

  if (path === "/api/constraints/evaluate") {
    return json(200, {
      status: "success",
      scale: body.scale || "lab",
      batch_size_kg: body.batch_size_kg || 0.1,
      constraints: constraints(),
      recommendations: ["Use temperature ramping", "Keep agitation above 400 rpm", "Verify solvent compatibility before scale-up"],
      equipment_requirements: ["jacketed reactor", "overhead stirrer", "addition funnel"],
    });
  }

  if (path === "/api/equipment/recommend") {
    return json(200, {
      status: "success",
      reactor_recommendations: [
        { name: "Jacketed glass reactor", score: 0.92, reasoning: "Best match for controlled heating and routine lab scale." },
        { name: "Round-bottom flask", score: 0.76, reasoning: "Suitable for small batches with simple reflux." },
      ],
      complete_setup: {
        reactor: "jacketed glass reactor",
        agitation: "overhead stirrer",
        temperature_control: "recirculating bath",
        pressure_rating_atm: Math.max(1, Number(body.pressure_atm || 1)),
      },
    });
  }

  if (path === "/api/templates/stats") {
    return json(200, { statistics: { total_types: 8, total_templates: 60, demo_mode: true } });
  }

  if (path === "/api/copilot/optimize") {
    return json(200, {
      answer: "Demo copilot: consider a greener solvent, controlled addition, and a lower thermal load before scale-up.",
      recommendations: [
        "Replace chlorinated solvent with 2-MeTHF where compatible.",
        "Run a small design-of-experiments screen around catalyst loading.",
        "Check heat release before moving beyond pilot scale.",
      ],
    });
  }

  if (path === "/api/routes/iterative-optimize") {
    const initial = 62;
    const final = 81;
    return json(200, {
      status: "converged",
      objective: body.objective || "balanced",
      pharma_mode: Boolean(body.pharma_mode),
      total_iterations: 3,
      total_improvement: final - initial,
      initial_score: initial,
      final_score: final,
      early_stopped: true,
      early_stop_reason: "Demo convergence threshold reached.",
      convergence_history: [
        { iteration: 1, score_before: 62, score_after: 70, improvement: 8 },
        { iteration: 2, score_before: 70, score_after: 77, improvement: 7 },
        { iteration: 3, score_before: 77, score_after: 81, improvement: 4 },
      ],
      best_routes: body.routes?.length ? body.routes : [demoRoute("CC(=O)Oc1ccccc1C(=O)O", 0)],
      total_duration_ms: 42.4,
    });
  }

  if (path === "/api/routes/yield-optimize") {
    return json(200, {
      status: "optimized",
      target_yield: Number(body.target_yield || 0.99),
      initial_yield: 0.65,
      final_yield: 0.82,
      yield_improvement: 0.17,
      yield_improvement_pct: 17,
      iterations_used: 3,
      step_yields: [0.82, 0.78],
      yield_bottleneck_step: 1,
      cost_analysis: { initial_cost: 350, final_cost: 330, loss_cost_initial: 122, loss_cost_final: 59, cost_saving_from_yield: 63 },
      scoring: { initial_score: 52, final_score: 78, score_formula: "yield^5 x 100 - cost_penalty - constraint_penalty - equipment_penalty" },
      optimization_history: [
        { iteration: 1, yield_before: 0.65, yield_after: 0.72, change: "solvent screen" },
        { iteration: 2, yield_before: 0.72, yield_after: 0.78, change: "temperature tuning" },
        { iteration: 3, yield_before: 0.78, yield_after: 0.82, change: "catalyst loading" },
      ],
      optimized_route: mutations(body.route || {}),
      pharma_mode: Boolean(body.pharma_mode),
      pharma_compliant: true,
      duration_ms: 38,
    });
  }

  return json(404, { detail: `Demo API has no route for ${path}` });
}

const server = http.createServer(async (req, res) => {
  try {
    const response = await route(req);
    res.writeHead(response.status, response.headers);
    res.end(response.status === 204 ? "" : response.body);
  } catch (error) {
    const response = json(500, { detail: error.message || "Demo API error" });
    res.writeHead(response.status, response.headers);
    res.end(response.body);
  }
});

server.listen(PORT, () => {
  console.log(`SynthAI demo API listening on http://localhost:${PORT}`);
});
